### ISSUE TITLE
[CVPR'24 Spotlight] State Space Models for Event Cameras

### ISSUE THREAD

**Issue by NikolaZubic** [XiudingCai/Awesome-Mamba-Collection#6]
Dear @XiudingCai , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:

https://arxiv.org/abs/2402.15584
https://github.com/uzh-rpg/ssms_event_cameras

Best,
Nikola.

**Comment by XiudingCai** [comment]
> Dear @XiudingCai , our work has been a spotlight at CVPR 2024. We would like if you could add it to the list:
> 
> https://arxiv.org/abs/2402.15584 https://github.com/uzh-rpg/ssms_event_cameras
> 
> Best, Nikola.

Hi Nikola,

We've added: (CVPR 2024 spotlight) State Space Models for Event Cameras [[paper](https://arxiv.org/abs/2402.15584)] [[code](https://github.com/uzh-rpg/ssms_event_cameras)] (2024.02.23).

Best,
Xiuding Cai.
