### ISSUE TITLE
[Architecture] S7: Selective and Simplified State Space Layers for Sequence Modeling

### ISSUE THREAD

**Issue by NikolaZubic** [XiudingCai/Awesome-Mamba-Collection#7]
Dear @XiudingCai ,

Here is our new paper on the S7 architecture:
S7: Selective and Simplified State Space Layers for Sequence Modeling
https://arxiv.org/abs/2410.03464

**Comment by XiudingCai** [comment]
Hi [@NikolaZubic](https://github.com/NikolaZubic),

Thanks for sharing! I've added your paper to the architecture section. I'll close this issue now.

Best,
Xiuding Cai
