### ISSUE TITLE
Mamba Meets Financial Markets: A Graph-Mamba Approach for Stock Price Prediction

### ISSUE THREAD

**Issue by Ali-Meh619** [XiudingCai/Awesome-Mamba-Collection#8]
Dear @XiudingCai ,

We submitted a paper with the title "Mamba Meets Financial Markets: A Graph-Mamba Approach for Stock Price Prediction". Here is the link to the arxiv version:
https://arxiv.org/abs/2410.03707

I would appreciate it if you can put that on your github account "Awesome-Mamba-Collection".

Thanks,
Ali

**Comment by XiudingCai** [comment]
Hi Ali,

Thanks for sharing! I've added your paper to both the Time Series and Graph sections. I'll close this issue now.

Best,  
Xiuding Cai
